In [169]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [170]:
# Loading the dataset
train_dataset = pd.read_csv('train.csv')
test_dataset = pd.read_csv('test.csv')

In [171]:
train_dataset

id  person_age  person_income person_home_ownership  \
0          0          37          35000                  RENT   
1          1          22          56000                   OWN   
2          2          29          28800                   OWN   
3          3          30          70000                  RENT   
4          4          22          60000                  RENT   
...      ...         ...            ...                   ...   
58640  58640          34         120000              MORTGAGE   
58641  58641          28          28800                  RENT   
58642  58642          23          44000                  RENT   
58643  58643          22          30000                  RENT   
58644  58644          31          75000              MORTGAGE   

       person_emp_length loan_intent loan_grade  loan_amnt  loan_int_rate  \
0                    0.0   EDUCATION          B       6000          11.49   
1                    6.0     MEDICAL          C       4000          13.35   
2                    8.0    PERSONAL          A       6000           8.90   
3                   14.0     VENTURE          B      12000          11.11   
4                    2.0     MEDICAL          A       6000           6.92   
...                  ...         ...        ...        ...            ...   
58640                5.0   EDUCATION          D      25000          15.95   
58641                0.0     MEDICAL          C      10000          12.73   
58642                7.0   EDUCATION          D       6800          16.00   
58643                2.0   EDUCATION          A       5000           8.90   
58644                2.0     VENTURE          B      15000          11.11   

       loan_percent_income cb_person_default_on_file  \
0                     0.17                         N   
1                     0.07                         N   
2                     0.21                         N   
3                     0.17                         N   
4                     0.10                         N   
...                    ...                       ...   
58640                 0.21                         Y   
58641                 0.35                         N   
58642                 0.15                         N   
58643                 0.17                         N   
58644                 0.20                         N   

       cb_person_cred_hist_length  loan_status  
0                              14            0  
1                               2            0  
2                              10            0  
3                               5            0  
4                               3            0  
...                           ...          ...  
58640                          10            0  
58641                           8            1  
58642                           2            1  
58643                           3            0  
58644                           5            0  

[58645 rows x 13 columns]

In [172]:
test_dataset

id  person_age  person_income person_home_ownership  \
0      58645          23          69000                  RENT   
1      58646          26          96000              MORTGAGE   
2      58647          26          30000                  RENT   
3      58648          33          50000                  RENT   
4      58649          26         102000              MORTGAGE   
...      ...         ...            ...                   ...   
39093  97738          22          31200              MORTGAGE   
39094  97739          22          48000              MORTGAGE   
39095  97740          51          60000              MORTGAGE   
39096  97741          22          36000              MORTGAGE   
39097  97742          31          45000                  RENT   

       person_emp_length        loan_intent loan_grade  loan_amnt  \
0                    3.0    HOMEIMPROVEMENT          F      25000   
1                    6.0           PERSONAL          C      10000   
2                    5.0            VENTURE          E       4000   
3                    4.0  DEBTCONSOLIDATION          A       7000   
4                    8.0    HOMEIMPROVEMENT          D      15000   
...                  ...                ...        ...        ...   
39093                2.0  DEBTCONSOLIDATION          B       3000   
39094                6.0          EDUCATION          A       7000   
39095                0.0           PERSONAL          A      15000   
39096                4.0           PERSONAL          D      14000   
39097                6.0  DEBTCONSOLIDATION          B      19450   

       loan_int_rate  loan_percent_income cb_person_default_on_file  \
0              15.76                 0.36                         N   
1              12.68                 0.10                         Y   
2              17.19                 0.13                         Y   
3               8.90                 0.14                         N   
4              16.32                 0.15                         Y   
...              ...                  ...                       ...   
39093          10.37                 0.10                         N   
39094           6.03                 0.15                         N   
39095           7.51                 0.25                         N   
39096          15.62                 0.39                         Y   
39097           9.91                 0.44                         N   

       cb_person_cred_hist_length  
0                               2  
1                               4  
2                               2  
3                               7  
4                               4  
...                           ...  
39093                           4  
39094                           3  
39095                          25  
39096                           4  
39097                           9  

[39098 rows x 12 columns]

In [173]:
# Splitting the dataset into the Training set and Test set
X = train_dataset.iloc[:, 1:-1].values
X

array([[37, 35000, 'RENT', ..., 0.17, 'N', 14],
       [22, 56000, 'OWN', ..., 0.07, 'N', 2],
       [29, 28800, 'OWN', ..., 0.21, 'N', 10],
       ...,
       [23, 44000, 'RENT', ..., 0.15, 'N', 2],
       [22, 30000, 'RENT', ..., 0.17, 'N', 3],
       [31, 75000, 'MORTGAGE', ..., 0.2, 'N', 5]], dtype=object)

In [ ]:
y = train_dataset.iloc[:, -1].values
y

In [128]:
# Performing Label Encoding for Categorical Data
# 1. person_home_ownership (Column 2)
# 2. loan_intent (Column 4)
# 3. loan_grade (Column 5)
# 4. cb_person_default_on_file (Column 9)

In [129]:
encoder = LabelEncoder()
X[:, 2] = encoder.fit_transform(X[:, 2])
X[:, 4] = encoder.fit_transform(X[:, 4])
X[:, 5] = encoder.fit_transform(X[:, 5])
X[:, 9] = encoder.fit_transform(X[:, 9])

In [130]:
X

array([[37, 35000, 3, ..., 0.17, 0, 14],
       [22, 56000, 2, ..., 0.07, 0, 2],
       [29, 28800, 2, ..., 0.21, 0, 10],
       ...,
       [23, 44000, 3, ..., 0.15, 0, 2],
       [22, 30000, 3, ..., 0.17, 0, 3],
       [31, 75000, 0, ..., 0.2, 0, 5]], dtype=object)

In [131]:
# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)

In [132]:
# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [167]:
# Training the Logistic Regression model on the Training set
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

In [168]:
# Making the Confusion Matrix
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

ValueError: Found input variables with inconsistent numbers of samples: [17594, 39098]

In [135]:
# Making performance metrics
from sklearn.metrics import f1_score
f1_score(y_test, y_pred, average='micro')

np.float64(0.8951915425713312)

In [136]:
# Making predictions from test dataset
X_test = test_dataset.iloc[:, 1:].values
X_test

array([[23, 69000, 'RENT', ..., 0.36, 'N', 2],
       [26, 96000, 'MORTGAGE', ..., 0.1, 'Y', 4],
       [26, 30000, 'RENT', ..., 0.13, 'Y', 2],
       ...,
       [51, 60000, 'MORTGAGE', ..., 0.25, 'N', 25],
       [22, 36000, 'MORTGAGE', ..., 0.39, 'Y', 4],
       [31, 45000, 'RENT', ..., 0.44, 'N', 9]], dtype=object)

In [137]:
# Performing Label Encoding for Categorical Data
X_test[:, 2] = encoder.fit_transform(X_test[:, 2])
X_test[:, 4] = encoder.fit_transform(X_test[:, 4])
X_test[:, 5] = encoder.fit_transform(X_test[:, 5])
X_test[:, 9] = encoder.fit_transform(X_test[:, 9])

In [138]:
# Performing Feature Scaling
new_X_test = sc.transform(X_test)

In [139]:
# Making predictions
new_y_pred = classifier.predict(new_X_test)
new_y_pred

array([1, 0, 1, ..., 0, 1, 1])

In [140]:
new_y_pred.shape

(39098,)

In [141]:
y_test.shape

(17594,)

In [145]:
new_y_pred_data = new_y_pred[:17594]

In [146]:
new_y_pred_data.shape

(17594,)

In [147]:
# Now evaluating the model with new testing dataset using f1_score
f1_score(y_test, new_y_pred_data, average='micro')

np.float64(0.7992497442309878)

In [148]:
# Visualising the Test set results
from sklearn.metrics import recall_score, precision_score, f1_score, accuracy_score
recall = recall_score(y_test, new_y_pred_data, average='micro')
precision = precision_score(y_test, new_y_pred_data, average='micro')
f1 = f1_score(y_test, new_y_pred_data, average='micro')
accuracy = accuracy_score(y_test, new_y_pred_data)

In [153]:
print(recall)
print(precision)
print(f1)
print(accuracy)

0.7992497442309878
0.7992497442309878
0.7992497442309878
0.7992497442309878
